export { default as Dashboard } from './Dashboard'
export { default as Devices } from './Devices'
export { default as Alerts } from './Alerts'
export { default as Analytics } from './Analytics'
export { default as Login } from './Login'
export { default as Settings } from './Settings'
export { default as Admin } from './Admin'
